### ISSUE TITLE
Related approaches

### ISSUE THREAD

**Issue by matbesancon** [JuliaDiff/SparseDiffTools.jl#1]
The paper we were discussing is this one:
https://link.springer.com/article/10.1007/s12532-018-0139-4

Describing a framework for differential equations, with sparse Jacobian handling through graph coloring

**Comment by ChrisRackauckas** [comment]
This is a great resource as well: https://pdfs.semanticscholar.org/ae4d/65769b6551a51d6fc6be2f021515bffa0798.pdf

**Comment by mauro3** [comment]
When I did my implementation in https://github.com/mauro3/MatrixColorings.jj, apparently I followed https://dl.acm.org/citation.cfm?id=2513110, which is by the same people as Chris' citation.  Also, in the readme I referred to [Hossain, S. and Steihaug, T. 2012](http://www.tandfonline.com/doi/abs/10.1080/10556788.2012.693927) as "state of the art".  However, I'm not sure how I came to that conclusion as I am anything but an expert.

**Comment by huanglangwen** [comment]
JuMP guys did similar things as well: https://github.com/mlubin/ReverseDiffSparse.jl

**Comment by ChrisRackauckas** [comment]
Yes. That is on the JuMP DSL and only for Hessians. We will probably implement a similar coloring algorithm, but then hook into Zygote so it's more language-wide.

**Comment by ChrisRackauckas** [comment]
http://www.ii.uib.no/~lennart/drgrad/Walther2008.pdf
https://www.cs.purdue.edu/homes/apothen/Papers/hessian-coloring-joc.pdf
https://pdfs.semanticscholar.org/4607/e817d51b97e2eefc42e8c8d83a335bb58f94.pdf
https://m.tau.ac.il/~stoledo/CSC07/GebremedhinPothenTarafdarWalther.pdf
https://www.researchgate.net/publication/220411486_New_Acyclic_and_Star_Coloring_Algorithms_with_Application_to_Computing_Hessians
https://www.cs.purdue.edu/homes/agebreme/publications/colpack-toms.pdf

**Comment by ChrisRackauckas** [comment]
https://ampl.com/REFS/ad96.pdf
