### ISSUE TITLE
matrix_colors can overwrite input (remove stored zeros)

### ISSUE THREAD

**Issue by sjdaines** [JuliaDiff/SparseDiffTools.jl#144]
The culprit would appear to be:

     function matrix2graph(sparse_matrix::SparseMatrixCSC{<:Number, Int}, partition_by_rows::Bool=true)

        dropzeros!(sparse_matrix)

Not sure what the correct fix is.   Perhaps two reasonable options ?
1. test for stored zeros, and error if present, or
2. treat stored zeros as structural nonzeros

However silently calling dropzeros! and modifying the input is surely wrong...

**Comment by ChrisRackauckas** [comment]
Oh, that `dropzeros!` is just wrong. Thanks for finding it. We should remove that. Coloring should only be w.r.t. structural zeros.

**Comment by ChrisRackauckas** [comment]
Thanks a lot. This is a good find.
