### ISSUE TITLE
Examples in README.md rely on deprecated package

### ISSUE THREAD

**Issue by ferrolho** [JuliaDiff/SparseDiffTools.jl#150]
The examples shown in the README.md rely on [SparsityDetection.jl](https://github.com/SciML/SparsityDetection.jl), which has been deprecated:
> Note: This repo has been deprecated in favor of ModelingToolkit.jl which can similarly inspect code and detect sparsity patterns.

Is that okay, or should the examples be rewritten with [ModelingToolkit.jl](https://github.com/SciML/ModelingToolkit.jl)?

**Comment by ChrisRackauckas** [comment]
The examples should probably be rewritten directly with Symbolics.jl, which is where that functionality now lives (oh boy, things are moving fast in the abstract interpreter space haha). Though Symbolics.jl is still missing a crucial part of the interface. 

https://symbolics.juliasymbolics.org/dev/manual/sparsity_detection/

We should add a dispatch which acts just like SparsityDetection.jl's, i.e. directly on the user function, so they don't have to do the tracing themselves. Adding that dispatch is probably the place to start, and then the update of this is trivial.
