### ISSUE TITLE
Documentation offline

### ISSUE THREAD

**Issue by lassepe** [JuliaDiff/SparseDiffTools.jl#211]
When I try to view the documentation at https://docs.sciml.ai/SparseDiffTools/stable/ I just see this:
![image](https://user-images.githubusercontent.com/10076790/201028337-53e59b6f-3c53-40f4-bd73-9d20c9a40534.png)

**Comment by ChrisRackauckas** [comment]
This should do it.

@JuliaRegistrator register()
