### ISSUE TITLE
Todos for v2

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiff/SparseDiffTools.jl#215]
- [ ] Make Zygote an extension package
- [ ] Make autodiff a multi-valued logic 

@Vaibhavdixit02 I think we may want to move `AutoZyogte()` and etc. types to a package that both this and Optimization.jl build off of?

**Comment by Vaibhavdixit02** [comment]
Yes, that will be quite useful for Optimization.jl

**Comment by vpuri3** [comment]
Hi @Vaibhavdixit02 @ChrisRackauckas, any news on this front? Thanks! :D

**Comment by Vaibhavdixit02** [comment]
I'll create the repo today @vpuri3

**Comment by Vaibhavdixit02** [comment]
https://github.com/JuliaRegistries/General/pull/78584
