### ISSUE TITLE
Docs currently failing to load

### ISSUE THREAD

**Issue by stmorgenstern** [JuliaDiff/SparseDiffTools.jl#239]
Currently getting a 403 forbidden error while trying to load the docs

`
403 Forbidden

    Code: AccessDenied
    Message: Access Denied
    RequestId: JR84VM6TW6DQKMKC
    HostId: GufTRU4qXYRtHv6TzgX+ULXJB5XED8ATqf5dTHHGhHme++U4kNaBocboCv7wG1cHVDm3A1F8TXU=

`

**Comment by ranocha** [comment]
Got the same error
